AminoAcids<-function()
   {
    aa3<-c("Lys","Asn","Lys","Asn","Thr","Thr","Thr","Thr","Arg","Ser","Arg","Ser","Ile","Ile","Met","Ile","Gln","His","Gln","His","Pro","Pro","Pro","Pro","Arg","Arg","Arg","Arg","Leu","Leu","Leu","Leu","Glu","Asp","Glu","Asp","Ala","Ala","Ala","Ala","Gly","Gly","Gly","Gly","Val","Val","Val","Val","Tyr","Tyr","Ser","Ser","Ser","Ser","Cys","Trp","Cys","Leu","Phe","Leu","Phe","Amb","Och","Opl")
    aa1<-c("K","N","K","N","T","T","T","T","R","S","R","S","I","I","M","I","Q","H","Q","H","P","P","P","P","R","R","R","R","L","L","L","L","E","D","E","D","A","A","A","A","G","G","G","G","V","V","V","V","Y","Y","S","S","S","S","C","W","C","L","F","L","F","*","*","*")
    codon<-c("AAA","AAC","AAG","AAT","ACA","ACC","ACG","ACT","AGA","AGC","AGG","AGT","ATA","ATC","ATG","ATT","CAA","CAC","CAG","CAT","CCA","CCC","CCG","CCT","CGA","CGC","CGG","CGT","CTA","CTC","CTG","CTT","GAA","GAC","GAG","GAT","GCA","GCC","GCG","GCT","GGA","GGC","GGG","GGT","GTA","GTC","GTG","GTT","TAC","TAT","TCA","TCC","TCG","TCT","TGC","TGG","TGT","TTA","TTC","TTG","TTT","TAG","TAA","TGA")
    aalong<-c("Lysine","Asparagine","Lysine","Asparagine","Threonine","Threonine","Threonine","Threonine","Arginine","Serine","Arginine","Serine","Isoleucine","Isoleucine","Methionine","Isoleucine","Glutamine","Histidine","Glutamine","Histidine","Proline","Proline","Proline","Proline","Arginine","Arginine","Arginine","Arginine","Leucine","Leucine","Leucine","Leucine","Glutamic acid","Aspartic acid","Glutamic acid","Aspartic acid","Alanine","Alanine","Alanine","Alanine","Glycine","Glycine","Glycine","Glycine","Valine","Valine","Valine","Valine","Tyrosine","Tyrosine","Serine","Serine","Serine","Serine","Cysteine","Tryptophan","Cysteine","Leucine","Phenylalanine","Leucine","Phenylalanine","Amber","Ochre","Opal")
    polarity<-c("polar","polar","polar","polar","polar","polar","polar","polar","polar","polar","polar","polar","nonpolar","nonpolar","nonpolar","nonpolar","polar","polar","polar","polar","nonpolar","nonpolar","nonpolar","nonpolar","polar","polar","polar","polar","nonpolar","nonpolar","nonpolar","nonpolar","polar","polar","polar","polar","nonpolar","nonpolar","nonpolar","nonpolar","nonpolar","nonpolar","nonpolar","nonpolar","nonpolar","nonpolar","nonpolar","nonpolar","polar","polar","polar","polar","polar","polar","nonpolar","nonpolar","nonpolar","nonpolar","nonpolar","nonpolar","nonpolar","","","")
    sidecharge<-c("positive","neutral","positive","neutral","neutral","neutral","neutral","neutral","positive","neutral","positive","neutral","neutral","neutral","neutral","neutral","neutral","positive","neutral","positive","neutral","neutral","neutral","neutral","positive","positive","positive","positive","neutral","neutral","neutral","neutral","negative","negative","negative","negative","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","neutral","","","")
    all<-as.data.frame(cbind(aa3,aa1,codon,aalong,polarity,sidecharge),stringsAsFactors=FALSE)
  return(all)
    }
